# Generated by Django 4.0.6 on 2022-07-19 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='book',
            new_name='isbn',
        ),
        migrations.AlterField(
            model_name='comment',
            name='reg_date',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
