# Generated by Django 4.0.6 on 2022-07-15 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reg_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
