# Generated by Django 4.0.6 on 2022-07-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_user_comment_email_rename_book_comment_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reg_date',
            field=models.TextField(),
        ),
    ]
